const toolbarDefaults = {
  options: [
    'inline',
    'fontSize',
    'colorPicker',
    'textAlign',
    'list',
    'image',
    'history',
    // 'blockType',
    // 'fontFamily',
    // 'link',
    // 'embedded',
    // 'remove',
    // 'emoji',
  ],
  inline: {
    inDropdown: true,
    className: 'icon-wrapper-light',
    component: undefined,
    dropdownClassName: 'dropdown-light',
    options: [
      'bold',
      'italic',
      'underline',
      'strikethrough',
      'monospace',
      'superscript',
      'subscript',
    ],
    bold: { icon: 'icons-light/B.svg', className: undefined },
    italic: { icon: 'icons-light/italic.svg', className: undefined },
    underline: { icon: 'icons-light/underline.svg', className: undefined },
    strikethrough: {
      icon: 'icons-light/strikethrough.svg',
      className: undefined,
    },
    monospace: { icon: 'icons-light/monospace.svg', className: undefined },
    superscript: { icon: 'icons-light/superscript.svg', className: undefined },
    subscript: { icon: 'icons-light/subscript.svg', className: undefined },
  },
  image: {
    icon: 'icons-light/frame.svg',
    className: 'icon-wrapper-light',
    component: undefined,
    popupClassName: 'image-popup-light',
    urlEnabled: true,
    uploadEnabled: true,
    alignmentEnabled: true,
    uploadCallback: undefined,
    previewImage: false,
    inputAccept: 'image/gif,image/jpeg,image/jpg,image/png,image/svg',
    alt: { present: false, mandatory: false },
    defaultSize: {
      height: 'auto',
      width: 'auto',
    },
  },
  history: {
    inDropdown: true,
    className: 'icon-wrapper-light',
    component: undefined,
    dropdownClassName: 'dropdown-light',
    options: ['undo', 'redo'],
    undo: { icon: 'icons-light/undo.svg', className: undefined },
    redo: { icon: 'icons-light/redo.svg', className: undefined },
  },
  fontSize: {
    // icon: fontSize,
    options: [8, 9, 10, 11, 12, 14, 16, 18, 24, 30, 36, 48, 60, 72, 96],
    className: 'icon-wrapper-light',
    component: undefined,
    dropdownClassName: 'dropdown-light',
  },
  list: {
    inDropdown: true,
    className: 'icon-wrapper-light',
    component: undefined,
    dropdownClassName: 'dropdown-light',
    options: ['unordered', 'ordered', 'indent', 'outdent'],
    unordered: { icon: 'icons-light/dottedList.svg', className: undefined },
    ordered: { icon: 'icons-light/orderedList.svg', className: undefined },
    indent: { icon: 'icons-light/indent.svg', className: undefined },
    outdent: { icon: 'icons-light/outdent.svg', className: undefined },
  },
  textAlign: {
    inDropdown: true,
    className: 'icon-wrapper-light',
    component: undefined,
    dropdownClassName: 'dropdown-light',
    options: ['left', 'center', 'right', 'justify'],
    left: { icon: 'icons-light/leftAlign.svg', className: undefined },
    center: { icon: 'icons-light/centerAlign.svg', className: undefined },
    right: { icon: 'icons-light/rightAlign.svg', className: undefined },
    justify: { icon: 'icons-light/blockAlign.svg', className: undefined },
  },
  colorPicker: {
    icon: 'icons-light/pen.svg',
    className: 'icon-wrapper-light',
    component: undefined,
    popupClassName: 'colorpicker-popup-light',
    colors: [
      'rgb(97,189,109)',
      'rgb(26,188,156)',
      'rgb(84,172,210)',
      'rgb(44,130,201)',
      'rgb(147,101,184)',
      'rgb(71,85,119)',
      'rgb(204,204,204)',
      'rgb(65,168,95)',
      'rgb(0,168,133)',
      'rgb(61,142,185)',
      'rgb(41,105,176)',
      'rgb(85,57,130)',
      'rgb(40,50,78)',
      'rgb(0,0,0)',
      'rgb(247,218,100)',
      'rgb(251,160,38)',
      'rgb(235,107,86)',
      'rgb(226,80,65)',
      'rgb(163,143,132)',
      'rgb(239,239,239)',
      'rgb(255,255,255)',
      'rgb(250,197,28)',
      'rgb(243,121,52)',
      'rgb(209,72,65)',
      'rgb(184,49,47)',
      'rgb(124,112,107)',
      'rgb(209,213,216)',
    ],
  },
  //   blockType: {
  //     inDropdown: true,
  //     options: [
  //       'Normal',
  //       'H1',
  //       'H2',
  //       'H3',
  //       'H4',
  //       'H5',
  //       'H6',
  //       'Blockquote',
  //       'Code',
  //     ],
  //     className: undefined,
  //     component: undefined,
  //     dropdownClassName: 'dropdown-light',
  //   },

  //   fontFamily: {
  //     options: [
  //       'Arial',
  //       'Georgia',
  //       'Impact',
  //       'Tahoma',
  //       'Times New Roman',
  //       'Verdana',
  //     ],
  //     className: undefined,
  //     component: undefined,
  //     dropdownClassName: 'dropdown-light',
  //   },

  //   link: {
  //     inDropdown: true,
  //     className: undefined,
  //     component: undefined,
  //     popupClassName: undefined,
  //     dropdownClassName: 'dropdown-light',
  //     showOpenOptionOnHover: true,
  //     defaultTargetOption: '_self',
  //     options: ['link', 'unlink'],
  //     // link: { icon: link, className: undefined },
  //     // unlink: { icon: unlink, className: undefined },
  //     linkCallback: undefined,
  //   },
  //   emoji: {
  //     // icon: emoji,
  //     className: undefined,
  //     component: undefined,
  //     popupClassName: undefined,
  //     emojis: [
  //       '😀',
  //       '😁',
  //       '😂',
  //       '😃',
  //       '😉',
  //       '😋',
  //       '😎',
  //       '😍',
  //       '😗',
  //       '🤗',
  //       '🤔',
  //       '😣',
  //       '😫',
  //       '😴',
  //       '😌',
  //       '🤓',
  //       '😛',
  //       '😜',
  //       '😠',
  //       '😇',
  //       '😷',
  //       '😈',
  //       '👻',
  //       '😺',
  //       '😸',
  //       '😹',
  //       '😻',
  //       '😼',
  //       '😽',
  //       '🙀',
  //       '🙈',
  //       '🙉',
  //       '🙊',
  //       '👼',
  //       '👮',
  //       '🕵',
  //       '💂',
  //       '👳',
  //       '🎅',
  //       '👸',
  //       '👰',
  //       '👲',
  //       '🙍',
  //       '🙇',
  //       '🚶',
  //       '🏃',
  //       '💃',
  //       '⛷',
  //       '🏂',
  //       '🏌',
  //       '🏄',
  //       '🚣',
  //       '🏊',
  //       '⛹',
  //       '🏋',
  //       '🚴',
  //       '👫',
  //       '💪',
  //       '👈',
  //       '👉',
  //       '👉',
  //       '👆',
  //       '🖕',
  //       '👇',
  //       '🖖',
  //       '🤘',
  //       '🖐',
  //       '👌',
  //       '👍',
  //       '👎',
  //       '✊',
  //       '👊',
  //       '👏',
  //       '🙌',
  //       '🙏',
  //       '🐵',
  //       '🐶',
  //       '🐇',
  //       '🐥',
  //       '🐸',
  //       '🐌',
  //       '🐛',
  //       '🐜',
  //       '🐝',
  //       '🍉',
  //       '🍄',
  //       '🍔',
  //       '🍤',
  //       '🍨',
  //       '🍪',
  //       '🎂',
  //       '🍰',
  //       '🍾',
  //       '🍷',
  //       '🍸',
  //       '🍺',
  //       '🌍',
  //       '🚑',
  //       '⏰',
  //       '🌙',
  //       '🌝',
  //       '🌞',
  //       '⭐',
  //       '🌟',
  //       '🌠',
  //       '🌨',
  //       '🌩',
  //       '⛄',
  //       '🔥',
  //       '🎄',
  //       '🎈',
  //       '🎉',
  //       '🎊',
  //       '🎁',
  //       '🎗',
  //       '🏀',
  //       '🏈',
  //       '🎲',
  //       '🔇',
  //       '🔈',
  //       '📣',
  //       '🔔',
  //       '🎵',
  //       '🎷',
  //       '💰',
  //       '🖊',
  //       '📅',
  //       '✅',
  //       '❎',
  //       '💯',
  //     ],
  //   },
  //   embedded: {
  //     // icon: embedded,
  //     className: undefined,
  //     component: undefined,
  //     popupClassName: undefined,
  //     embedCallback: undefined,
  //     defaultSize: {
  //       height: 'auto',
  //       width: 'auto',
  //     },
  //   },
  //   remove: { icon: eraser, className: undefined, component: undefined },
};

export default toolbarDefaults;
